---

- name: Create libbitcoin work directory
  file: path={{ libbitcoin_work_dir }} state=directory

- name: Create libbitcoin install directory
  file: path={{ libbitcoin_prefix }} state=directory
  when: libbitcoin_prefix is defined

- name: Download libbitcoin installer
  get_url:
    url: https://raw.githubusercontent.com/libbitcoin/libbitcoin/version3/install.sh
    dest: '{{ libbitcoin_work_dir }}/install.sh'
    mode: u+x

- name: Execute libbitcoin install.sh
  shell: chdir={{ libbitcoin_work_dir }} ./install.sh